# Generated by Django 2.2.4 on 2020-07-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(unique=True, verbose_name='Company Id')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Company Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Company Overview')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Store Name')),
                ('timer_turn_yellow', models.IntegerField(default=5, verbose_name='Service Timer Turn Yellow (in mins)')),
                ('timer_turn_red', models.IntegerField(default=10, verbose_name='Service Timer Turn Red (in mins)')),
                ('timer_escalation_to_manager', models.IntegerField(default=12, verbose_name='Escalation to manager (in mins)')),
                ('logo', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Store Logo Image')),
                ('order_url', models.TextField(blank=True, null=True, verbose_name='Place New Order URL')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Company')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item', models.ManyToManyField(blank=True, related_name='store_service_item', to='store.ServiceItem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'verbose_name': 'Store Service Item',
                'verbose_name_plural': 'Store Service Items',
            },
        ),
    ]
