# Generated by Django 2.2.4 on 2020-07-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200726_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='service_item',
            field=models.ManyToManyField(blank=True, related_name='store_service_item', to='store.ServiceItem'),
        ),
        migrations.DeleteModel(
            name='StoreServiceItem',
        ),
    ]
