# Generated by Django 2.2.4 on 2020-07-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200726_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_seat', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Table/Seat',
                'verbose_name_plural': 'Tables/Seats',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='table_seat',
            field=models.ManyToManyField(blank=True, related_name='store_table_seat', to='store.TableSeat'),
        ),
    ]
