# Generated by Django 2.2.4 on 2020-07-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200726_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTableStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_seat', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=25)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'verbose_name': 'Table/Seat',
                'verbose_name_plural': 'Tables/Seats',
            },
        ),
    ]
