# Generated by Django 2.2.4 on 2020-07-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200729_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetablestatus',
            name='table_seat',
            field=models.CharField(max_length=10),
        ),
    ]
