# Generated by Django 2.2.4 on 2020-08-04 08:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200730_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ip_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
