# Generated by Django 2.2.4 on 2020-08-04 09:05

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_ip_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='ip_addresses',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
