# Generated by Django 2.2.4 on 2020-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200804_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='specific_phone_number_prefix',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Specific Phone Number Prefix'),
        ),
    ]
