# Generated by Django 2.2.4 on 2020-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_company_specific_phone_number_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sms_text_guest_alert',
            field=models.BooleanField(default=False, verbose_name='SMS Text Guest Alert'),
        ),
    ]
