# Generated by Django 2.2.4 on 2020-08-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_store_screen_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='survey_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Survey URL'),
        ),
    ]
