# Generated by Django 2.2.4 on 2020-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_store_survey_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='specific_phone_number_prefix',
            field=models.CharField(default='', max_length=25, verbose_name='Specific Phone Number Prefix'),
        ),
    ]
