# Generated by Django 2.2.4 on 2020-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200814_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Dining Type',
                'verbose_name_plural': 'Dining Types',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='dining_type',
            field=models.ManyToManyField(blank=True, related_name='store_dining_type', to='store.DiningType'),
        ),
    ]
