# Generated by Django 2.2.4 on 2020-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_store_order_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='order_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name="Order Rank# (0 indicates that 'Place a New Order' button is shown at all times)"),
        ),
    ]
