# Generated by Django 2.2.4 on 2020-08-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200826_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableseat',
            name='table_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Unique Table ID(store and table)'),
        ),
        migrations.AlterField(
            model_name='tableseat',
            name='table_seat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pure Table/Seat Name'),
        ),
    ]
