# Generated by Django 2.2.4 on 2020-08-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200828_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableseat',
            name='table_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Unique Table ID(Format: {Store#}.{Table/Seat} (for example, 1.1.1 or 1.1.B1))'),
        ),
        migrations.AlterField(
            model_name='tableseat',
            name='table_seat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pure Table/Seat Name(For example, 1 or B1)'),
        ),
    ]
