# Generated by Django 2.2.4 on 2020-09-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200828_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Table Status (ex. Available)')),
            ],
            options={
                'verbose_name': 'Table Status',
                'verbose_name_plural': 'Table Status',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='wait_time_frame',
            field=models.IntegerField(default=10, verbose_name='Wait Time Frame for getting longest/average wait time'),
        ),
        migrations.AddField(
            model_name='tableseat',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.DiningType'),
        ),
        migrations.AddField(
            model_name='tableseat',
            name='seats',
            field=models.IntegerField(default=1, verbose_name='Number of Seats'),
        ),
        migrations.AddField(
            model_name='tableseat',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Status'),
        ),
    ]
