# Generated by Django 2.2.4 on 2020-09-14 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_diningtype_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableseat',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
