# Generated by Django 2.2.4 on 2020-09-16 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_tableseat_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableseat',
            name='status',
        ),
        migrations.AddField(
            model_name='tableseat',
            name='last_time_customer_tap',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Last time customer tapped'),
        ),
        migrations.AddField(
            model_name='tableseat',
            name='last_time_status_changed',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Last time table status changed'),
        ),
        migrations.AddField(
            model_name='tableseat',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Actual time order is received'),
        ),
        migrations.AddField(
            model_name='tableseat',
            name='seated_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Actual time table is seated'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
