# Generated by Django 2.2.4 on 2020-09-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20200916_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableseat',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning'), ('Closed', 'Closed')], default='Open', max_length=25),
        ),
        migrations.DeleteModel(
            name='StoreTableStatus',
        ),
    ]
