# Generated by Django 2.2.4 on 2020-09-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20200916_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableseat',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning')], default='Available', max_length=25),
        ),
    ]
