# Generated by Django 2.2.4 on 2020-09-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20200917_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableseat',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=25),
        ),
    ]
