# Generated by Django 2.2.4 on 2020-09-24 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_tableseat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableseat',
            name='last_time_customer_tap',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Last time customer tapped'),
        ),
        migrations.AlterField(
            model_name='tableseat',
            name='last_time_status_changed',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Last time table status changed'),
        ),
        migrations.AlterField(
            model_name='tableseat',
            name='ordered_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Actual time order is received'),
        ),
        migrations.AlterField(
            model_name='tableseat',
            name='seated_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Actual time table is seated'),
        ),
    ]
