# Generated by Django 2.2.4 on 2020-09-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20200924_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableseat',
            name='curside_message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Message for 'Delivering to Car/Curbside' type"),
        ),
        migrations.AddField(
            model_name='tableseat',
            name='pickup_message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Message for 'Pickup & Bar' type"),
        ),
    ]
