# Generated by Django 2.2.4 on 2020-09-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20200925_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableseat',
            name='curside_message',
        ),
        migrations.RemoveField(
            model_name='tableseat',
            name='pickup_message',
        ),
    ]
