# Generated by Django 2.2.4 on 2020-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20200925_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='curside_message',
            field=models.CharField(default='', max_length=100, verbose_name="Message for 'Delivering to Car/Curbside' type"),
        ),
        migrations.AddField(
            model_name='store',
            name='pickup_message',
            field=models.CharField(default='', max_length=100, verbose_name="Message for 'Pickup & Bar' type"),
        ),
    ]
