# Generated by Django 2.2.4 on 2020-06-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('store_id', models.CharField(blank=True, max_length=50, null=True)),
                ('table_id', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('action_date_gmt', models.CharField(blank=True, max_length=50, null=True)),
                ('package_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('newsletter', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('q1', models.CharField(blank=True, max_length=50, null=True)),
                ('a1', models.CharField(blank=True, max_length=50, null=True)),
                ('q2', models.CharField(blank=True, max_length=50, null=True)),
                ('a2', models.CharField(blank=True, max_length=50, null=True)),
                ('q3', models.CharField(blank=True, max_length=50, null=True)),
                ('a3', models.CharField(blank=True, max_length=50, null=True)),
                ('q4', models.CharField(blank=True, max_length=50, null=True)),
                ('a4', models.CharField(blank=True, max_length=50, null=True)),
                ('q5', models.CharField(blank=True, max_length=50, null=True)),
                ('a5', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
