# Generated by Django 2.2.4 on 2020-07-18 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('store_id', models.CharField(blank=True, max_length=25, null=True)),
                ('table_id', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('session_token', models.CharField(blank=True, max_length=512, null=True)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UBIRWiFi',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=25, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=25, null=True)),
                ('action_date_gmt', models.DateTimeField(default=datetime.datetime.now)),
                ('package_id', models.CharField(blank=True, max_length=25, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.CharField(blank=True, max_length=25, null=True)),
                ('newsletter', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('zip', models.CharField(blank=True, max_length=25, null=True)),
                ('country_code', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('q1', models.CharField(blank=True, max_length=50, null=True)),
                ('a1', models.CharField(blank=True, max_length=50, null=True)),
                ('q2', models.CharField(blank=True, max_length=50, null=True)),
                ('a2', models.CharField(blank=True, max_length=50, null=True)),
                ('q3', models.CharField(blank=True, max_length=50, null=True)),
                ('a3', models.CharField(blank=True, max_length=50, null=True)),
                ('q4', models.CharField(blank=True, max_length=50, null=True)),
                ('a4', models.CharField(blank=True, max_length=50, null=True)),
                ('q5', models.CharField(blank=True, max_length=50, null=True)),
                ('a5', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'UBIR WiFi Login History',
                'verbose_name_plural': 'UBIR WiFi Login Histories',
            },
        ),
    ]
