# Generated by Django 2.2.4 on 2020-06-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='county_code',
            new_name='country_code',
        ),
    ]
