# Generated by Django 2.2.4 on 2020-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
