# Generated by Django 2.2.4 on 2020-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200821_0144'),
        ('customer', '0002_customer_is_in_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dining_type',
            field=models.ManyToManyField(blank=True, related_name='customer_dining_type', to='store.DiningType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_in_party',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
