# Generated by Django 2.2.4 on 2020-06-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200626_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='store_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='table_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
