# Generated by Django 2.2.4 on 2020-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200826_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='parking_space',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Parking Space #'),
        ),
    ]
