# Generated by Django 2.2.4 on 2020-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_parking_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='parking_space',
            field=models.CharField(default='', max_length=25, verbose_name='Parking Space #'),
        ),
    ]
