# Generated by Django 2.2.4 on 2020-09-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200925_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='parking_space',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Parking Space #'),
        ),
    ]
