# Generated by Django 2.2.4 on 2020-10-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200926_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned',
            field=models.BooleanField(default=False, verbose_name='True if a customer is assigned, not seated in Host Wait List'),
        ),
    ]
