# Generated by Django 2.2.4 on 2020-10-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_table_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
