# Generated by Django 2.2.4 on 2020-10-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_assigned_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='waked',
            field=models.BooleanField(default=True),
        ),
    ]
