# Generated by Django 2.2.4 on 2020-10-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_waked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='seated',
            field=models.BooleanField(default=False),
        ),
    ]
