# Generated by Django 2.2.4 on 2020-08-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=25, null=True, verbose_name='Company Name')),
                ('store', models.CharField(blank=True, max_length=25, null=True, verbose_name='Store Name')),
                ('login', models.CharField(blank=True, max_length=25, null=True, verbose_name='Customer Phone Number')),
                ('tap', models.CharField(blank=True, max_length=25, null=True, verbose_name='Tap')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Log',
                'verbose_name_plural': 'Customer Logs',
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=25, null=True, verbose_name='Company Name')),
                ('store', models.CharField(blank=True, max_length=25, null=True, verbose_name='Store Name')),
                ('login', models.CharField(blank=True, max_length=25, null=True, verbose_name='Staff Username')),
                ('tap', models.CharField(blank=True, max_length=25, null=True, verbose_name='Tap')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Log',
                'verbose_name_plural': 'Service Logs',
            },
        ),
    ]
