# Generated by Django 2.2.4 on 2020-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20200817_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlog',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content'),
        ),
    ]
