# Generated by Django 2.2.4 on 2020-08-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20200818_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Content'),
        ),
    ]
