# Generated by Django 2.2.4 on 2020-08-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200818_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlog',
            name='session_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='session_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
