# Generated by Django 2.2.4 on 2020-07-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Store ID')),
                ('type', models.CharField(blank=True, choices=[('QUESTION', 'QUESTION'), ('ANSWER', 'ANSWER')], max_length=25, null=True)),
                ('table_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Table Seat Number')),
                ('item_title', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
