# Generated by Django 2.2.4 on 2020-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flash',
            field=models.BooleanField(default=True),
        ),
    ]
