# Generated by Django 2.2.4 on 2020-08-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicemanconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceman',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
    ]
