# Generated by Django 2.2.4 on 2020-08-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200805_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceman',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
