# Generated by Django 2.2.4 on 2020-08-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200811_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceman',
            old_name='approved',
            new_name='active',
        ),
    ]
