# Generated by Django 2.2.4 on 2020-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200812_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceman',
            name='curbside',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceman',
            name='host',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceman',
            name='togo',
            field=models.BooleanField(default=True),
        ),
    ]
