# Generated by Django 2.2.4 on 2020-08-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INPROGRESS', 'INPROGRESS'), ('INPROGRESS_PENDING', 'INPROGRESS_PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=25),
        ),
    ]
